# Generated by Django 4.2.17 on 2024-12-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('tags', models.JSONField()),
            ],
        ),
    ]
