# Generated by Django 5.1.4 on 2024-12-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("tags", models.JSONField(default=dict)),
                ("tag_preferences", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                ("interaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("report", "Report"),
                        ],
                        max_length=255,
                    ),
                ),
                ("interaction_time", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="preferences.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="preferences.user",
                    ),
                ),
            ],
        ),
    ]
