# Generated by Django 5.1.4 on 2024-12-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0003_alter_interaction_interaction_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="interaction_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
