# Generated by Django 5.1.4 on 2024-12-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0004_alter_interaction_interaction_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interaction",
            options={"ordering": ["-interaction_time"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["post_id"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["user_id"]},
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["post_id"], name="post_post_id_4e620a_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_id"], name="user_user_id_31c9cf_idx"),
        ),
        migrations.AlterModelTable(
            name="interaction",
            table="interaction",
        ),
        migrations.AlterModelTable(
            name="post",
            table="post",
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
