# Generated by Django 5.1.4 on 2024-12-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0005_alter_interaction_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
