# Generated by Django 5.1.4 on 2024-12-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0006_alter_post_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="tag_preferences",
            new_name="preferences",
        ),
    ]
