# Generated by Django 5.1.4 on 2024-12-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0007_rename_tag_preferences_user_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.AlterField(
            model_name="user",
            name="preferences",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="tags",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="preferences.tag"),
        ),
    ]
