# Generated by Django 5.1.4 on 2024-12-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0009_alter_tag_options_alter_tag_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tags_name",
            new_name="name",
        ),
    ]
